const sampleListings = [
  {
    title: "Cozy Apartment 1",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 2",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 3",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 4",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 5",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 6",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 7",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 8",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 9",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 10",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 11",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 12",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 13",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 14",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 15",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 16",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 17",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 18",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 19",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 20",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 21",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 22",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 23",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 24",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 25",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 26",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 27",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 28",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 29",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 30",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 31",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 32",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 33",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 34",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 35",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 36",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 37",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 38",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 39",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 40",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 41",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 42",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 43",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 44",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 45",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 46",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 47",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 48",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 49",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 50",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 51",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 52",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 53",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 54",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 55",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 56",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 57",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 58",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 59",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 60",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 61",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 62",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 63",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 64",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 65",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 66",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 67",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 68",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 69",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 70",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 71",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 72",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 73",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 74",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 75",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 76",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 77",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 78",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 79",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 80",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 81",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 82",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 83",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 84",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 85",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 86",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 87",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 88",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 89",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 90",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 91",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 92",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 93",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 94",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 95",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 96",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 97",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 98",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 99",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 100",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 101",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 102",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 103",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 104",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 105",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 106",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 107",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 108",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 109",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 110",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 111",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 112",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 113",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 114",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 115",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 116",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 117",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 118",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 119",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 120",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 121",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 122",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 123",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 124",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 125",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 126",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 127",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 128",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 129",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 130",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 131",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 132",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 133",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 134",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 135",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 136",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 137",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 138",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 139",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 140",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 141",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 142",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 143",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 144",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 145",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 146",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 147",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 148",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 149",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 150",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 151",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 152",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 153",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 154",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 155",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 156",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 157",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 158",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 159",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 160",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 161",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 162",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 163",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 164",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 165",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 166",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 167",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 168",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 169",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 170",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 171",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 172",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 173",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 174",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 175",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 176",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 177",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 178",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 179",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 180",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 181",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 182",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 183",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 184",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 185",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 186",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 187",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 188",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 189",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 190",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 191",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 192",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 193",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 194",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 195",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Cozy Apartment 196",
    description: "This is a beautiful cozy apartment perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa 197",
    description: "This is a beautiful luxury villa perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Modern Loft 198",
    description: "This is a beautiful modern loft perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Beach House 199",
    description: "This is a beautiful beach house perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mountain Cabin 200",
    description: "This is a beautiful mountain cabin perfect for a comfortable stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Goa",
    country: "India",
  },
];

module.exports = sampleListings;
